### PR TITLE
use node manager token instead mcm

### LINKED ISSUE #12233: [MCM] Use bootstrap token generated by Deckhouse
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.67.12

### Expected Behavior

It is required that a token generated by Deckhouse is used when adding nodes to the cluster.

### Actual Behavior

Nowadays, we use a token generated by MCM, which is limited to a duration of 20 minutes. This can cause undesirable consequences in situations where nodes take a long time to be provisioned. There have cases instances where a node started with an already expired token.

### Steps To Reproduce

_No response_

### Additional Information

_No response_

### Logs

```shell

```

### PR DESCRIPTION
**Pull request by d2285**
**What this PR does / why we need it**:
this mr allow to use node-manager boostrap token instead mcm token.
**Which issue(s) this PR fixes**:
resolve [this](https://github.com/deckhouse/deckhouse/issues/12233) issue
**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

File: pkg/controller/machine_bootstrap_token.go [hunk 1]
```diff
@@ -56,41 +58,61 @@ func (c *controller) addBootstrapTokenToUserData(machineName string, driver driv
...
+func (c *controller) getBootstrapTokenOrCreateIfNotExist(machineLabels map[string]string, machineName string) (secret *v1.Secret, err error) {
+	value, ok := machineLabels["instance-group"]
+	if !ok || value == "" {
+		return nil, fmt.Errorf("missing instance-group label from machine: '%v'", machineName)
+	}
+	octets := strings.Split(value, "-")
+	if len(octets) == 0 {
+		return nil, fmt.Errorf("failed to get nodegroup name from machine: '%v'", machineName)
+	}
+	labelSelector := fmt.Sprintf("node-manager.deckhouse.io/node-group=%s", octets[0])
```
Comment (name212) [inline pkg/controller/machine_bootstrap_token.go]: label `instance-group` contains node group + zone. In the node group we can have dash symbol, for example `worker-big`
image
image

in this case we will get `worker` instead of `worker-big`. Also zone also can have dash symbol, for yandex, for example. Working with split function will be hard to extract zone name.

I suggest get ng name from spec in the machine. from nodeTemplate
image

File: pkg/controller/machine_bootstrap_token.go [hunk 2]
```diff
@@ -56,41 +58,61 @@ func (c *controller) addBootstrapTokenToUserData(machineName string, driver driv
...
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      secretName,
+			Namespace: metav1.NamespaceSystem,
+		},
+		Type: bootstraptokenapi.SecretTypeBootstrapToken,
+		Data: data,
+	}
 
-	return secret, nil
+	return c.targetCoreClient.CoreV1().Secrets(metav1.NamespaceSystem).Create(secret)
```
Comment (name212) [inline pkg/controller/machine_bootstrap_token.go:154]: why do we need to create separate secret yet, when we have extract token from secret directly?

File: pkg/controller/machine_bootstrap_token.go [hunk 3]
```diff
@@ -56,41 +58,61 @@ func (c *controller) addBootstrapTokenToUserData(machineName string, driver driv
...
 }
 
-func (c *controller) getBootstrapTokenOrCreateIfNotExist(machineName string) (secret *v1.Secret, err error) {
-	tokenID, secretName := getTokenIDAndSecretName(machineName)
-
-	secret, err = c.targetCoreClient.CoreV1().Secrets(metav1.NamespaceSystem).Get(secretName, metav1.GetOptions{})
+func (c *controller) getBootstrapTokenOrCreateIfNotExist(machineLabels map[string]string, machineName string) (secret *v1.Secret, err error) {
+	value, ok := machineLabels["instance-group"]
+	if !ok || value == "" {
+		return nil, fmt.Errorf("missing instance-group label from machine: '%v'", machineName)
```
Comment (name212) [inline pkg/controller/machine_bootstrap_token.go]: let add fall back to old creating secret if we have errors and log with warning in this cases

File: pkg/controller/machine_bootstrap_token.go [hunk 4]
```diff
@@ -56,41 +58,61 @@ func (c *controller) addBootstrapTokenToUserData(machineName string, driver driv
...
+	}
+	octets := strings.Split(value, "-")
+	if len(octets) == 0 {
+		return nil, fmt.Errorf("failed to get nodegroup name from machine: '%v'", machineName)
+	}
+	labelSelector := fmt.Sprintf("node-manager.deckhouse.io/node-group=%s", octets[0])
+	secretListNodeManager, err := c.targetCoreClient.CoreV1().Secrets(metav1.NamespaceSystem).List(metav1.ListOptions{
```
Comment (name212) [inline pkg/controller/machine_bootstrap_token.go:96]: let to add retry function with 5 retries and sleep 3 second

**Review by name212 — CHANGES_REQUESTED** [review]
some nits

File: pkg/controller/machine_bootstrap_token.go (hunk 2 above)
Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go:154]: yes, you are right. this is return old logic when we got 0 secrets bootstraped from node-manager and filtered by label,it  will return generated secret by mcm and use it

Comment (name212) [reply pkg/controller/machine_bootstrap_token.go:154]: good point for all error cases
https://github.com/deckhouse/mcm/pull/16/files#r2041817825

File: pkg/controller/machine_bootstrap_token.go (hunk 1 above)
Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go]: changed scrape nodegroup name from machine.Spec.NodeTemplateSpec.Labels, it will return consist value from label node.deckhouse.io/group,ex.
```
"node.deckhouse.io/group" == "worker-with-separator"
```

File: pkg/controller/machine_bootstrap_token.go (hunk 2 above)
Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go:154]: added separate func for create bootstrap token by mcm if get 0 tokens generated by node-manager

File: pkg/controller/machine_bootstrap_token.go (hunk 3 above)
Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go]: was added

File: pkg/controller/machine_bootstrap_token.go (hunk 4 above)
Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go:96]: was added retry loop from func addBootstrapTokenToUserData

File: pkg/controller/machine_bootstrap_token.go (hunk 2 above)
Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go:154]: fallback was checked
```
I0414 14:34:27.052500       1 machine.go:433] Creating machine "denisenko-devtest-10-worker-with-separator-ac6881fa-66b8b-mljq6", please wait!
W0414 14:34:27.072632       1 machine_bootstrap_token.go:112] failed to get bootstrap token created by node-manager
Creating bootstrap token from MCM!
...
I0414 14:45:14.394970       1 machine.go:1012] Machine denisenko-devtest-10-worker-with-separator-ac6881fa-66b8b-mljq6 successfully joined the cluster
```

**Review by sprait — APPROVED** [review]

File: pkg/controller/machine_bootstrap_token.go [hunk 5]
```diff
@@ -56,41 +73,76 @@ func (c *controller) addBootstrapTokenToUserData(machineName string, driver driv
 	return nil
 }
 
-func (c *controller) getBootstrapTokenOrCreateIfNotExist(machineName string) (secret *v1.Secret, err error) {
-	tokenID, secretName := getTokenIDAndSecretName(machineName)
-
-	secret, err = c.targetCoreClient.CoreV1().Secrets(metav1.NamespaceSystem).Get(secretName, metav1.GetOptions{})
+func (c *controller) getBootstrapTokenOrCreateIfNotExist(machineLabels map[string]string, machineName string) (secret *v1.Secret, err error) {
+	value, ok := machineLabels["node.deckhouse.io/group"]
```
Comment (name212) [inline pkg/controller/machine_bootstrap_token.go:86]: let check machineLabels != nil

Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go:86]: add if machineLabels == nil  return warn and create mcm token

Comment (d2285) [reply pkg/controller/machine_bootstrap_token.go:86]: fixed

**Review by name212 — APPROVED** [review]
